/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
static yyconst short int yy_accept[317] =
    {   0,
        0,    0,   59,   57,    2,    3,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   55,   56,   55,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,    4,   57,   57,   57,   57,   57,   57,    2,   54,
        0,   53,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    1,   47,    0,   57,   57,
       57,   49,   57,    0,    0,   57,   57,   55,   57,   57,
       57,   57,   57,   57,   57,    9,   57,   57,   57,   57,
       57,   57,    6,   57,   57,   15,   13,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    1,    0,    0,    0,   57,   46,   57,   57,
       57,   12,   57,   57,   57,   57,   57,   10,   57,   57,
       57,   57,   14,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       48,   41,   57,   57,   17,   57,   57,   57,    8,   57,
       57,   40,   16,   57,    4,   57,   57,   57,    7,    5,
        0,    0,    0,    0,    0,    0,    0,   32,    0,   21,
       27,    0,    0,    0,   50,    0,   57,   57,   57,   57,

       57,   11,   57,   57,   39,   57,   52,    0,    0,   20,
       30,    0,   33,    0,    0,    0,    0,    0,   41,   45,
       57,   57,   40,   57,   57,   57,   52,    0,   19,    0,
       18,    0,    0,    0,    0,    0,    0,    0,   57,   44,
       57,   57,   39,   57,   52,    0,    0,   28,    0,    0,
        0,   26,    0,    0,   45,   57,   57,   42,   57,   57,
       57,   57,   31,    0,   25,   24,   22,    0,    0,   44,
       43,   57,   57,   57,   57,   57,    0,    0,   51,   57,
       42,   57,   36,   57,   57,    0,    0,   43,   57,   38,
       57,   57,   34,   29,    0,   57,   57,   36,   57,   57,

        0,   57,   38,   57,   34,   23,   35,   57,   57,   57,
       35,   57,   37,   57,   37,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    1,    1,    1,
        1,    1,    7,    1,    8,    9,   10,   11,   12,   13,
       14,   15,   15,   16,   16,   16,   17,   18,    1,   19,
       20,   21,    1,   22,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   30,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
        1,    1,    1,    1,   23,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   33,   30,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,    1,    1,    1,    1,    1,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   50,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   50,   49,   49,   49,   49,
       49,    1,    1,   51,   52,   52,   52,   52,   52,   52,

       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   53,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    3,    1,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1,    4,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[337] =
    {   0,
        0,    0,  747,  748,  744,  748,  725,  739,  721,   43,
       44,  732,   83,  730,  124,  131,  138,  720,  719,  718,
      150,  138,  703,   39,  699,   40,   40,  706,  697,  139,
      705,  689,   34,   57,   47,  703,  699,   52,  727,  748,
      723,  748,  705,    0,  160,  151,  136,  156,  161,  110,
      158,  177,  160,  166,  167,    0,  748,  210,  217,  226,
        0,    0,  683,  699,  674,  705,  180,  748,  682,  221,
      694,  677,  695,  684,  677,    0,  675,  688,  686,  679,
      686,  679,    0,  668,  680,    0,    0,  668,  675,  672,
      672,  670,  667,  674,  658,  664,  671,  748,  689,   61,

      184,  185,  193,  115,  186,  224,  225,  165,  226,  228,
      227,  231,    0,  259,  243,  240,  651,  748,  668,  655,
      670,    0,  659,  656,  654,  650,  661,    0,  648,  646,
      649,  648,    0,  643,  641,  645,  644,  648,  638,  642,
      649,  634,  639,  306,  245,  244,  257,  258,  259,  187,
      260,  263,  264,  265,  266,  267,  273,  319,  325,  295,
        0,  651,  638,  628,    0,  645,  630,  645,    0,  621,
      639,  643,    0,  633,    0,  631,  623,  625,    0,    0,
      336,  280,  269,  306,  277,  270,  303,  639,  332,  638,
      637,  274,  237,  333,  748,  648,  353,  633,  619,  618,

      627,    0,  356,  629,  629,  611,  372,  345,  335,  628,
      348,  336,  627,   71,  344,  368,  369,  381,  391,  625,
      599,  603,  394,  609,  399,  621,  415,  355,  621,  374,
      620,  387,  382,  392,  395,  389,  624,  629,  426,  616,
      598,  587,  432,  411,  593,  425,  414,  579,  421,  422,
      138,  578,  454,  461,  472,  475,  575,  575,  554,  553,
      558,  566,  570,  463,  569,  564,  428,  475,  487,  499,
      562,  502,  548,  534,  532,  540,  430,  471,  748,  507,
      510,  494,  537,  527,  519,  498,  501,  527,  529,  531,
      530,  518,  528,  508,  415,  504,  533,  536,  494,  539,

      528,  498,  555,  484,  559,  474,  472,  427,  562,  419,
      565,  423,  435,  571,  581,  748,  603,  605,  452,  609,
      409,  371,  611,  613,  323,  615,   58,  617,  619,  621,
      623,  625,  627,  629,  631,  633
    } ;

static yyconst short int yy_def[337] =
    {   0,
      316,    1,  316,  316,  316,  316,  316,  317,  318,  318,
      318,  316,  316,   13,   13,   13,   13,  316,  316,  316,
       13,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,  316,  316,  316,
      317,  316,  318,  319,   10,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  320,  316,   10,   13,   13,
       21,   21,   21,  316,  316,   60,   60,  316,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,  316,  319,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  320,   10,  316,  316,   21,  316,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,  321,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  316,  316,  316,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
      322,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  316,  316,  323,   21,   21,   21,

       21,   21,  324,   21,   21,   21,  325,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  316,  323,   21,
       21,   21,  324,   21,  326,   21,  327,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  316,  316,  328,   21,
       21,   21,  326,   21,  319,  318,  318,  318,  318,  318,
      318,  318,  316,  316,  328,  329,   21,   21,   21,   21,
       21,   21,  318,  318,  318,  318,  318,  316,  316,  329,
       21,  330,   21,   21,   21,   21,  318,  318,  316,  331,
      330,   21,   21,   21,   21,  318,  318,  331,   21,   21,
      332,   21,   21,  318,  318,   21,  333,  332,   21,  334,

      318,   21,  333,   21,  334,  318,   21,   21,  335,   21,
      335,   21,   21,  336,  336,    0,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316
    } ;

static yyconst short int yy_nxt[802] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   17,   17,    4,   18,   19,
       20,    4,   21,   22,   23,   24,   25,   26,   27,   21,
       21,   28,   21,   21,   21,   29,   30,   31,   32,   33,
       34,   35,   21,   36,   37,   21,   21,   21,    4,    4,
       38,   38,    4,   45,   45,   45,   45,   45,   45,   45,
      245,   90,   74,   80,   44,   44,   75,   46,   47,   48,
       91,   49,   50,   77,   51,   78,   81,   94,   52,   82,
       92,   53,   44,   79,   93,   54,   95,   55,   57,   43,
       43,   58,   44,   59,   60,   60,   60,   60,   60,   60,

       98,   98,  145,  232,   44,   61,   61,   61,   61,   61,
       61,   61,   61,   62,   61,   61,   63,   62,   61,   61,
       61,   61,   61,   62,   61,   61,   61,   61,   61,   61,
       61,   44,   64,   65,   60,   64,   44,  105,   66,   66,
       66,   66,   66,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,  316,  149,   44,   43,   44,
       61,   61,   61,   61,   61,   61,   61,   85,   58,   69,
      267,   70,   44,   71,   86,  101,  100,   44,   87,   44,
       61,   44,   44,   61,   61,   72,   44,   44,   44,  316,
       61,  153,  102,  111,  106,  103,  110,  316,   44,  316,

      316,  104,  316,  112,  107,   44,   44,   44,   44,   64,
       65,  150,   64,  108,   44,  146,  148,  187,  147,  109,
      114,  114,  114,  114,  114,  114,  114,   67,   67,   67,
       67,   67,   67,   67,  115,  116,   67,   67,   67,   67,
       67,   67,   67,  115,  120,   44,   44,   44,   44,   44,
      159,  160,   44,  158,  158,  158,  158,  158,   44,  216,
      152,  156,  121,  151,  157,   44,   44,  154,  155,  114,
      114,  114,  114,  114,  114,  114,  182,  183,   44,   44,
       44,   44,  186,  188,   44,   44,   44,   44,   44,  185,
       44,   44,  191,  184,   44,   44,  212,  192,   44,  215,

      190,   44,  209,  189,  193,  196,  196,  196,   64,   65,
      211,   64,   99,   99,  144,  194,   99,   99,   99,   99,
       99,   99,   99,  208,   44,  227,  213,   44,   99,  195,
      195,  195,  195,  195,  195,  195,  196,  196,  196,  196,
      196,  196,   99,   99,  144,  210,   99,   99,   99,   99,
       99,   99,   99,   44,   44,  214,   44,   44,   99,   43,
       43,   43,   43,   43,   43,   44,   44,  217,  228,   44,
      230,  229,  231,  207,   44,  233,   44,   44,   99,   99,
      144,  246,   99,   99,   99,   99,   99,   99,   99,   44,
       44,  234,  237,  238,   99,   44,  236,   43,   43,   43,

       43,   43,   43,   44,  235,   43,   43,   43,   44,  247,
       44,  181,   44,   44,  248,   44,   44,  250,  249,  251,
       44,   99,   99,  144,  252,   99,   99,   99,   99,   99,
       99,   99,   43,   43,   43,   44,   44,   99,   43,   43,
       43,  259,   44,   44,  260,  261,   44,   44,  263,   44,
      264,   44,  262,   44,   99,  278,  265,  314,  301,  313,
      312,  286,  310,  266,  268,  268,  268,  268,  268,  268,
      268,  269,  269,  269,  269,  269,  269,  269,   43,   43,
       43,   43,   43,   43,   44,  279,  279,  279,  279,  279,
      279,  279,   44,   44,  309,   44,   44,  279,  279,  279,

      279,  279,  279,  279,  277,   43,   43,   43,   43,   43,
       43,  308,  287,   43,   43,   43,   43,   43,   43,   44,
       44,  289,   44,   44,  307,  304,  294,  302,   44,   44,
      290,   44,  295,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   44,   44,
      300,   44,  299,  297,   44,  296,  293,   44,  292,  291,
       44,   43,   43,   43,  306,   43,   43,   43,   43,   43,
       43,   43,   43,   43,  285,  284,   44,   43,   43,   43,
       44,  283,  282,   44,  280,   44,   44,   43,   43,   43,
       44,   44,   44,  276,  275,  274,  273,  272,  271,   44,

       44,  144,   44,   41,   41,   41,   41,   43,   43,  113,
      258,  113,  113,  219,  219,  223,  223,  243,  243,  255,
      255,  270,  270,  281,  281,  288,  288,  298,  298,  303,
      303,  305,  305,  311,  311,  315,  315,  257,  256,  254,
      253,   44,   44,  244,  242,  241,  240,  239,   44,   44,
      226,  225,  224,  222,  165,  221,  220,  218,   44,   44,
       44,  206,  175,  205,  204,  203,   86,  202,  201,  173,
      200,  199,  198,  197,  180,  173,   86,  179,  178,  177,
      165,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  144,  143,  142,

      141,  140,  139,  138,  137,  136,  135,  134,   86,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  119,  316,   64,  118,  117,   44,   42,   39,   97,
       96,   89,   88,   84,   83,   76,   73,   68,   40,   68,
       60,   56,   44,   42,   40,   39,  316,    3,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316
    } ;

static yyconst short int yy_chk[802] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   10,   10,   10,   10,   10,   10,   10,
      327,   33,   24,   27,   10,   11,   24,   11,   11,   11,
       33,   11,   11,   26,   11,   26,   27,   35,   11,   27,
       34,   11,  100,   26,   34,   11,   35,   11,   13,   13,
       13,   13,  214,   13,   13,   13,   13,   13,   13,   13,

       38,   38,  100,  214,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   50,   13,   13,   15,   13,  104,   50,   15,   15,
       15,   16,   16,   16,   16,   16,   16,   16,   17,   17,
       17,   17,   17,   17,   17,   21,  104,   47,   21,  251,
       21,   21,   21,   21,   21,   21,   21,   30,   45,   22,
      251,   22,   46,   22,   30,   47,   46,   48,   30,   51,
       21,   53,   49,   21,   21,   22,  108,   54,   55,   67,
       21,  108,   48,   54,   51,   49,   53,   67,   52,   21,

       21,   49,   21,   55,   52,  101,  102,  105,  150,   45,
       45,  105,   45,   52,  103,  101,  103,  150,  102,   52,
       58,   58,   58,   58,   58,   58,   58,   59,   59,   59,
       59,   59,   59,   59,   59,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   70,  106,  107,  109,  111,  110,
      116,  116,  112,  115,  115,  115,  115,  115,  193,  193,
      107,  111,   70,  106,  112,  146,  145,  109,  110,  114,
      114,  114,  114,  114,  114,  114,  145,  146,  147,  148,
      149,  151,  149,  151,  152,  153,  154,  155,  156,  148,
      183,  186,  154,  147,  157,  192,  186,  155,  185,  192,

      153,  182,  183,  152,  156,  160,  160,  160,  114,  114,
      185,  114,  144,  144,  144,  157,  144,  144,  144,  144,
      144,  144,  144,  182,  187,  325,  187,  184,  144,  158,
      158,  158,  158,  158,  158,  158,  159,  159,  159,  159,
      159,  159,  181,  181,  181,  184,  181,  181,  181,  181,
      181,  181,  181,  189,  194,  189,  209,  212,  181,  197,
      197,  197,  203,  203,  203,  215,  208,  194,  208,  211,
      211,  209,  212,  322,  197,  215,  228,  203,  207,  207,
      207,  228,  207,  207,  207,  207,  207,  207,  207,  216,
      217,  216,  218,  218,  207,  230,  217,  219,  219,  219,

      223,  223,  223,  233,  216,  225,  225,  225,  232,  230,
      236,  321,  219,  234,  232,  223,  235,  234,  233,  235,
      225,  227,  227,  227,  236,  227,  227,  227,  227,  227,
      227,  227,  239,  239,  239,  247,  295,  227,  243,  243,
      243,  244,  249,  250,  244,  244,  246,  239,  246,  267,
      247,  277,  244,  243,  319,  267,  249,  313,  295,  312,
      310,  277,  308,  250,  253,  253,  253,  253,  253,  253,
      253,  254,  254,  254,  254,  254,  254,  254,  255,  255,
      255,  256,  256,  256,  264,  268,  268,  268,  268,  268,
      268,  268,  278,  255,  307,  306,  256,  269,  269,  269,

      269,  269,  269,  269,  264,  270,  270,  270,  272,  272,
      272,  304,  278,  280,  280,  280,  281,  281,  281,  286,
      270,  282,  287,  272,  302,  299,  286,  296,  280,  294,
      282,  281,  287,  288,  288,  288,  291,  291,  291,  297,
      297,  297,  298,  298,  298,  300,  300,  300,  288,  301,
      293,  291,  292,  290,  297,  289,  285,  298,  284,  283,
      300,  303,  303,  303,  301,  305,  305,  305,  309,  309,
      309,  311,  311,  311,  276,  275,  303,  314,  314,  314,
      305,  274,  273,  309,  271,  266,  311,  315,  315,  315,
      265,  263,  314,  262,  261,  260,  259,  258,  257,  252,

      248,  245,  315,  317,  317,  317,  317,  318,  318,  320,
      242,  320,  320,  323,  323,  324,  324,  326,  326,  328,
      328,  329,  329,  330,  330,  331,  331,  332,  332,  333,
      333,  334,  334,  335,  335,  336,  336,  241,  240,  238,
      237,  231,  229,  226,  224,  222,  221,  220,  213,  210,
      206,  205,  204,  201,  200,  199,  198,  196,  191,  190,
      188,  178,  177,  176,  174,  172,  171,  170,  168,  167,
      166,  164,  163,  162,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  132,  131,  130,  129,  127,  126,
      125,  124,  123,  121,  120,  119,  117,   99,   97,   96,

       95,   94,   93,   92,   91,   90,   89,   88,   85,   84,
       82,   81,   80,   79,   78,   77,   75,   74,   73,   72,
       71,   69,   66,   65,   64,   63,   43,   41,   39,   37,
       36,   32,   31,   29,   28,   25,   23,   20,   19,   18,
       14,   12,    9,    8,    7,    5,    3,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\src\\Lexer.l"
#define INITIAL 0
/* Lexer - Equipo C.mánticos
   UTN FRRE - SSL 2026
*/ 
#line 9 ".\\src\\Lexer.l"
#include <stdio.h>
#include <stdlib.h>
#include <locale.h>
#ifdef _WIN32
#include <windows.h>
#include <fcntl.h>
#include <io.h>
#endif

int linea = 1;
/*----- Definiciones Regulares Básicas -----*/
/*----- Literales y Unidades -----*/
/*----- Identificadores de Actuadores (Prefijos Obligatorios, sufijos opcionales) -----*/
#line 670 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 44 ".\\src\\Lexer.l"

	/*----- Sección de Reglas ----------------*/

#line 825 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 317 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 748 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 ".\\src\\Lexer.l"
{ /* Ignoramos comentarios de una linea */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 ".\\src\\Lexer.l"
{ /* Ignoramos espacios en blanco */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 49 ".\\src\\Lexer.l"
{ linea++; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 50 ".\\src\\Lexer.l"
{ printf("Terminando modo interactivo\n"); exit(0); }
	YY_BREAK
/* Palabras Reservadas */
case 5:
YY_RULE_SETUP
#line 53 ".\\src\\Lexer.l"
{ printf("Token: TK_WHEN | Lexema: WHEN\n"); /* return WHEN; */ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 54 ".\\src\\Lexer.l"
{ printf("Token: TK_IF | Lexema: IF\n"); /* return IF; */ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 55 ".\\src\\Lexer.l"
{ printf("Token: TK_THEN | Lexema: THEN\n"); /* return THEN; */ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 56 ".\\src\\Lexer.l"
{ printf("Token: TK_ELSE | Lexema: ELSE\n"); /* return ELSE; */ }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 57 ".\\src\\Lexer.l"
{ printf("Token: TK_DO | Lexema: DO\n"); /* return DO; */ }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 58 ".\\src\\Lexer.l"
{ printf("Token: TK_END | Lexema: END\n"); /* return END; */ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 59 ".\\src\\Lexer.l"
{ printf("Token: TK_EVERY | Lexema: EVERY\n"); /* return EVERY; */ }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 60 ".\\src\\Lexer.l"
{ printf("Token: OP_LOGICO | Lexema: AND\n"); /* return AND; */ }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 61 ".\\src\\Lexer.l"
{ printf("Token: OP_LOGICO | Lexema: OR\n"); /* return OR; */ }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 62 ".\\src\\Lexer.l"
{ printf("Token: OP_LOGICO | Lexema: NOT\n"); /* return NOT; */ }
	YY_BREAK
/* Booleanos, Modos y Colores */
case 15:
YY_RULE_SETUP
#line 65 ".\\src\\Lexer.l"
{ printf("Token: BOOLEANO | Lexema:  %s\n", yytext); /* return BOOLEANO; */ }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 ".\\src\\Lexer.l"
{ printf("Token: MODO_AIRE | Lexema:  %s\n", yytext); /* return MODO_AIRE; */ }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 ".\\src\\Lexer.l"
{ printf("Token: VALOR_COLOR | Lexema:  %s\n", yytext); /* return VALOR_COLOR; */ }
	YY_BREAK
/* Atributos Dispositivos (Notación de punto) */
case 18:
YY_RULE_SETUP
#line 70 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  estado\n"); /* return ESTADO; */ }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  brillo\n"); /* return BRILLO; */ }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  color\n"); /* return COLOR; */ }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  modo\n"); /* return MODO; */ }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  temp_obj\n"); /* return TEMP_OBJ; */ }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  temp_objetivo\n"); /* return TEMP_OBJETIVO; */ }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  temp_act\n"); /* return TEMP_ACT; */ }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  posicion\n"); /* return POSICION; */ }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  volumen\n"); /* return VOLUMEN; */ }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  mute\n"); /* return MUTE; */ }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  mensaje\n"); /* return MENSAJE; */ }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 81 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  email_notif\n"); /* return EMAIL_NOTIF; */ }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 82 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  email\n"); /* return ATTR_EMAIL; */ }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 83 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  activada\n"); /* return ACTIVADA; */ }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 84 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  hora\n"); /* return ATTR_HORA; */ }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 85 ".\\src\\Lexer.l"
{ printf("Token: ATRIBUTO | Lexema:  fecha\n"); /* return ATTR_FECHA; */ }
	YY_BREAK
/* Sensores (Dispositivos de Entrada) */
case 34:
YY_RULE_SETUP
#line 88 ".\\src\\Lexer.l"
{ printf("Token: SENSOR_TEMPERATURA_ID | Lexema: %s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 ".\\src\\Lexer.l"
{ printf("Token: SENSOR_HUMEDAD_ID | Lexema: %s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 ".\\src\\Lexer.l"
{ printf("Token: SENSOR_LUZ_ID | Lexema: %s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 ".\\src\\Lexer.l"
{ printf("Token: SENSOR_MOVIMIENTO_ID | Lexema: %s\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 ".\\src\\Lexer.l"
{ printf("Token: SENSOR_HUMO_ID | Lexema: %s\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 93 ".\\src\\Lexer.l"
{ printf("Token: RELOJ_ID | Lexema: %s\n", yytext); }
	YY_BREAK
/* Actuadores (Dispositivos de Salida) */
case 40:
YY_RULE_SETUP
#line 96 ".\\src\\Lexer.l"
{ printf("Token: FOCO_ID | Lexema: %s\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 97 ".\\src\\Lexer.l"
{ printf("Token: AIRE_ID | Lexema: %s\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 98 ".\\src\\Lexer.l"
{ printf("Token: PERSIANA_ID | Lexema: %s\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 99 ".\\src\\Lexer.l"
{ printf("Token: CERRADURA_ID | Lexema: %s\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 100 ".\\src\\Lexer.l"
{ printf("Token: ALTAVOZ_ID | Lexema: %s\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 101 ".\\src\\Lexer.l"
{ printf("Token: ALARMA_ID | Lexema: %s\n", yytext); }
	YY_BREAK
/* Literales y Unidades Compuestas */
case 46:
YY_RULE_SETUP
#line 104 ".\\src\\Lexer.l"
{ 
    DWORD written;
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    char msg[512];
    int len = snprintf(msg, sizeof(msg), "Token: TEMPERATURA | Lexema: %s\n", yytext);
    WriteConsoleA(hOut, msg, len, &written, NULL);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 111 ".\\src\\Lexer.l"
{ printf("Token: PORCENTAJE | Lexema: %s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 112 ".\\src\\Lexer.l"
{ printf("Token: ILUMINANCIA | Lexema: %s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 113 ".\\src\\Lexer.l"
{ printf("Token: TIEMPO | Lexema: %s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 114 ".\\src\\Lexer.l"
{ printf("Token: VALOR_HORA | Lexema: %s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 115 ".\\src\\Lexer.l"
{ printf("Token: VALOR_FECHA | Lexema: %s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 116 ".\\src\\Lexer.l"
{ printf("Token: EMAIL | Lexema: %s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 117 ".\\src\\Lexer.l"
{ printf("Token: TEXTO | Lexema: %s\n", yytext); }
	YY_BREAK
/* Operadores y Delimitadores */
case 54:
YY_RULE_SETUP
#line 120 ".\\src\\Lexer.l"
{ printf("Token: OP_IGUALDAD | Lexema: %s\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 121 ".\\src\\Lexer.l"
{ printf("Token: OP_RELACIONAL | Lexema: %s\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 122 ".\\src\\Lexer.l"
{ printf("Token: ASIGNACION | Lexema: =\n"); }
	YY_BREAK
/* Control de errores léxicos unificado */
case 57:
YY_RULE_SETUP
#line 125 ".\\src\\Lexer.l"
{ 
#ifdef _WIN32
    DWORD written;
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    char msg[512];
    int len = snprintf(msg, sizeof(msg), "TOKEN_ERROR: %s (En linea %d)\n", yytext, linea);
    WriteConsoleA(hOut, msg, len, &written, NULL);
#else
    printf("TOKEN_ERROR: %s (En linea %d)\n", yytext, linea);
#endif
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 137 ".\\src\\Lexer.l"
ECHO;
	YY_BREAK
#line 1222 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 317 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 317 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 316);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 137 ".\\src\\Lexer.l"

	/*----- Sección de Procedimientos --------*/

int main(int argc, char *argv[]) {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
    SetConsoleCP(65001);
#endif
    setlocale(LC_ALL, "");

    if (argc == 2) {
        yyin = fopen(argv[1], "rt");
        if (yyin == NULL) {
            printf("Error: El archivo %s no se puede abrir\n", argv[1]);
            exit(-1);
        }
        printf("Analizando archivo: %s\n\n", argv[1]);
        yylex();
    } else {
        printf("--- Modo Interactivo Smart Home ---\n");
        printf("Escribe comandos o escribe 'quit', 'q' o 'salir' para terminar.\n");

#ifdef _WIN32
        HANDLE hIn = GetStdHandle(STD_INPUT_HANDLE);
        wchar_t wbuf[1024];
        char    ubuf[4096];
        SetConsoleOutputCP(65001);
        while (1) {
            DWORD nread = 0;
            if (!ReadConsoleW(hIn, wbuf, 1023, &nread, NULL) || nread == 0)
                break;
            wbuf[nread] = L'\0';

            /* Convertir UTF-16 a UTF-8 */
            int ulen = WideCharToMultiByte(CP_UTF8, 0, wbuf, -1,
                                           ubuf, sizeof(ubuf), NULL, NULL);
            if (ulen <= 0) continue;
            /* ulen incluye el \0 final, lo descartamos */
            ulen--;

            /* Pasarle el buffer a Flex */
            YY_BUFFER_STATE bs = yy_scan_bytes(ubuf, ulen);
            yylex();
            yy_delete_buffer(bs);
        }
#else
        yyin = stdin;
        yylex();
#endif
    }

    return 0;
}